apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: delta
  name: strim-frontend
  namespace: delta
spec:
  ingresses:
    - https://strim.ansatt.nav.no
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  env:
    - name: OBO_API_AUDIENCE
      value: "api://prod-gcp.delta.strim-backend/.default"

  accessPolicy:
    outbound:
      rules:
        - application: strim-backend
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      autoLogin: true
      enabled: true
