import type {Metadata} from "next";
import { Box } from "@navikt/ds-react";
import "@navikt/ds-css";
import "@/app/styles/tailwind.css"

import Header from "@/app/components/header";
import Footer from "@/app/components/footer";

export const metadata: Metadata = {
    title: "Skup",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
children: React.ReactNode;
}>) {
    return (
        <html lang="no">
        <body>
            <Header/>
            <Box className="w-5/6 max-w-[80rem] m-auto sm:px-5 mb-12 mt-10">{children}</Box>
            <Footer/>
        </body>
        </html>
    );
}
